use std::collections::BTreeMap;
use std::net::IpAddr;
use std::sync::Arc;
use std::sync::RwLock;

use aes::Aes128;
use aes::cipher::Array;
use aes::cipher::BlockCipherDecrypt;
use aes::cipher::BlockCipherEncrypt;
use aes::cipher::KeyInit;
use aws_lc_rs::rand::SecureRandom;
use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::KeyPair;
use aws_lc_rs::signature::RSA_PKCS1_2048_8192_SHA256;
use aws_lc_rs::signature::RSA_PKCS1_SHA256;
use aws_lc_rs::signature::RsaKeyPair;
use sha2::Digest;
use sha2::Sha256;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;
use tokio::sync::Notify;
use tokio::time::Instant;
use x509_parser::prelude::*;

use crate::state::PersistentState;

/// Bound retained certificates, challenge state and human approvals.
pub(crate) const MAX_PENDING_PAIRINGS: usize = 32;

/// A client that is not yet paired, but in the pairing process.
pub(crate) struct PendingClient {
	pub(crate) deadline: Instant,
	/// Unique id of the client.
	pub(crate) id: String,

	/// Client certificate used for secure communication (PEM format).
	pub(crate) pem: String,

	/// Salt provided by the client to use for encryption.
	pub(crate) salt: [u8; 16],

	/// A channel that sends a notification when a PIN has been received for this client.
	pub(crate) pin_notify: Arc<Notify>,

	/// Random token identifying this request on the operator approval page. A
	/// PIN applies only to the request the operator was shown, never to a later
	/// request that replaced it under the same client ID.
	pub(crate) approval: String,

	/// Address that sent the pairing request, shown to the operator.
	pub(crate) requester: IpAddr,

	/// Cryptographic key.
	pub(crate) key: Option<[u8; 16]>,

	/// Server secret as generated by the server.
	pub(crate) server_secret: Option<[u8; 16]>,

	/// Server challenge provided by the client.
	pub(crate) server_challenge: Option<[u8; 16]>,

	/// Cryptographic hash.
	pub(crate) client_hash: Option<Vec<u8>>,
}

/// A pending pairing request as presented to the operator.
pub(crate) struct PendingApproval {
	pub(crate) approval: String,
	pub(crate) requester: IpAddr,
	pub(crate) fingerprint: Option<String>,
}

/// Generate a pending request's approval token.
pub(crate) fn new_approval_token() -> Result<String, ()> {
	let mut token = [0u8; 16];
	SystemRandom::new()
		.fill(&mut token)
		.map_err(|_| tracing::warn!("Failed to generate random"))?;
	Ok(hex::encode(token))
}

/// Manages client pairing state and operations.
///
/// This is a synchronous manager backed by an `Arc<RwLock>`. It holds pending client state
/// (salt, certificates, challenge/response data) and delegates persistent state to `State`.
#[derive(Clone)]
pub struct ClientManager {
	pending_clients: Arc<RwLock<BTreeMap<String, PendingClient>>>,
	state: PersistentState,
	cleanup_started: Arc<AtomicBool>,
	pub(crate) authorization_gate: Arc<tokio::sync::RwLock<()>>,
	server_cert_pem: String,
	server_private_key_pem: String,
}

impl ClientManager {
	#[cfg(test)]
	pub(crate) fn isolated(path: std::path::PathBuf) -> Self {
		Self::isolated_with_identity(path, String::new(), String::new())
	}

	#[cfg(test)]
	pub(crate) fn isolated_with_identity(
		path: std::path::PathBuf,
		server_cert_pem: String,
		server_private_key_pem: String,
	) -> Self {
		Self {
			pending_clients: Default::default(),
			cleanup_started: Default::default(),
			authorization_gate: Default::default(),
			state: PersistentState::isolated(path),
			server_cert_pem,
			server_private_key_pem,
		}
	}

	#[cfg(test)]
	pub(crate) fn restarted(&self, path: std::path::PathBuf) -> Self {
		Self {
			state: PersistentState::load(path).unwrap(),
			pending_clients: Default::default(),
			cleanup_started: Default::default(),
			authorization_gate: Default::default(),
			..self.clone()
		}
	}

	pub fn new(server_cert_pem: String, server_private_key_pem: String) -> Result<Self, ()> {
		Ok(Self {
			pending_clients: Arc::new(RwLock::new(BTreeMap::new())),
			cleanup_started: Default::default(),
			authorization_gate: Default::default(),
			state: PersistentState::new()?,
			server_cert_pem,
			server_private_key_pem,
		})
	}

	pub fn persistent_state(&self) -> &PersistentState {
		&self.state
	}

	pub(crate) fn is_paired(&self, id: String) -> Result<bool, ()> {
		self.state.has_client(id)
	}

	pub(crate) fn is_cert_paired(&self, fingerprint: &str) -> Result<bool, ()> {
		self.state.has_paired_cert(fingerprint.to_string())
	}

	pub(crate) fn start_pairing(&self, pending_client: PendingClient) -> Result<(), ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		Self::expire(&mut inner);
		if pending_client.id.is_empty()
			|| pending_client.id.len() > 256
			|| pending_client.pem.len() > 16 * 1024
			|| cert_pem_fingerprint(&pending_client.pem).is_none()
		{
			return Err(());
		}
		if !inner.contains_key(&pending_client.id) && inner.len() >= MAX_PENDING_PAIRINGS {
			return Err(());
		}
		if let Some(old) = inner.insert(pending_client.id.clone(), pending_client) {
			old.pin_notify.notify_one();
		}
		Ok(())
	}

	fn expire(inner: &mut BTreeMap<String, PendingClient>) {
		inner.retain(|_, client| {
			if client.deadline <= Instant::now() {
				client.pin_notify.notify_one();
				false
			} else {
				true
			}
		});
	}

	/// One sweeper per manager, no per-transaction timer/task accumulation.
	pub(crate) fn ensure_cleanup(&self, shutdown: async_shutdown::ShutdownManager<crate::ShutdownReason>) {
		if self.cleanup_started.swap(true, Ordering::AcqRel) {
			return;
		}
		let Ok(delay) = shutdown.delay_shutdown_token() else {
			return;
		};
		let pending = Arc::downgrade(&self.pending_clients);
		tokio::spawn(async move {
			// Global shutdown completion includes clearing all pending state.
			let _delay = delay;
			loop {
				let stopping = tokio::select! {
					_ = shutdown.wait_shutdown_triggered() => true,
					_ = tokio::time::sleep(Duration::from_secs(1)) => false,
				};
				let Some(pending) = pending.upgrade() else {
					break;
				};
				if let Ok(mut inner) = pending.write() {
					if stopping {
						for client in inner.values() {
							client.pin_notify.notify_one();
						}
						inner.clear();
					} else {
						Self::expire(&mut inner);
					}
				}
				if stopping {
					break;
				}
			}
		});
	}

	pub(crate) fn approved(&self, id: &str, approval: &str) -> bool {
		self.pending_clients.read().ok().is_some_and(|inner| {
			inner.get(id).is_some_and(|client| {
				client.approval == approval && client.key.is_some() && client.deadline > Instant::now()
			})
		})
	}

	pub(crate) fn revoke(&self, id: Option<&str>, fingerprint: Option<&str>) -> Result<bool, ()> {
		// Serializes against completion: an already-approved transaction cannot
		// restore the credential just revoked. New requests need new approval.
		let mut inner = self.pending_clients.write().map_err(|_| ())?;
		let changed = self.state.revoke(id, fingerprint)?;
		if changed {
			for client in inner.values() {
				client.pin_notify.notify_one();
			}
			inner.clear();
		}
		Ok(changed)
	}

	/// Describe the pending request for `id` to the operator.
	pub(crate) fn pending_approval(&self, id: &str) -> Option<PendingApproval> {
		let inner = self
			.pending_clients
			.read()
			.map_err(|poison| tracing::error!("RwLock poisoned: {poison}"))
			.ok()?;
		let client = inner.get(id)?;
		if client.deadline <= Instant::now() {
			return None;
		}
		Some(PendingApproval {
			approval: client.approval.clone(),
			requester: client.requester,
			fingerprint: cert_pem_fingerprint(&client.pem),
		})
	}

	/// Forget a pending request that was not approved in time, unless it was
	/// already replaced by a newer request for the same client ID.
	pub(crate) fn cancel_pairing(&self, id: &str, approval: &str) {
		if let Ok(mut inner) = self.pending_clients.write()
			&& inner.get(id).is_some_and(|client| client.approval == approval)
			&& let Some(client) = inner.remove(id)
		{
			client.pin_notify.notify_one();
		}
	}

	/// Apply the operator's PIN to the pending request identified by `approval`.
	pub(crate) fn register_pin(&self, id: &str, pin: &str, approval: &str) -> Result<(), ()> {
		if pin.is_empty() || pin.len() > 16 || !pin.bytes().all(|b| b.is_ascii_digit()) {
			tracing::warn!("Rejected PIN that is not a short decimal number");
			return Err(());
		}
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		Self::expire(&mut inner);
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;
		if aws_lc_rs::constant_time::verify_slices_are_equal(client.approval.as_bytes(), approval.as_bytes()).is_err() {
			tracing::warn!("PIN submission does not match the displayed pairing request for {id}");
			return Err(());
		}
		if client.key.is_some() {
			tracing::warn!("A PIN was already registered for this pairing request");
			return Err(());
		}
		let key = create_key(&client.salt, pin).map_err(|e| tracing::warn!("Failed to create client key: {e}"))?;
		client.key = Some(key);
		client.pin_notify.notify_one();
		Ok(())
	}

	pub(crate) fn client_challenge(
		&self,
		id: &str,
		generation: Option<&str>,
		challenge: Vec<u8>,
	) -> Result<Vec<u8>, ()> {
		if challenge.len() != 16 {
			return Err(());
		}
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		Self::expire(&mut inner);
		if inner
			.get(id)
			.is_none_or(|client| generation != Some(client.approval.as_str()))
		{
			return Err(());
		}
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;

		if client.server_challenge.is_some() {
			return Err(());
		}

		let key = match &client.key {
			Some(key) => key,
			None => {
				tracing::warn!("Client has not provided a pin yet.");
				return Err(());
			},
		};

		let mut server_secret = [0u8; 16];
		SystemRandom::new()
			.fill(&mut server_secret)
			.map_err(|_| tracing::warn!("Failed to generate random"))?;
		client.server_secret = Some(server_secret);

		let mut decrypted =
			aes_decrypt_ecb(&challenge, key).map_err(|e| tracing::warn!("Failed to decrypt client challenge: {e}"))?;

		let signature_bytes = extract_certificate_signature(&self.server_cert_pem)
			.map_err(|e| tracing::warn!("Failed to extract server cert signature: {e}"))?;
		decrypted.extend_from_slice(&signature_bytes);
		decrypted.extend_from_slice(&server_secret);

		let mut server_challenge = [0u8; 16];
		SystemRandom::new()
			.fill(&mut server_challenge)
			.map_err(|_| tracing::warn!("Failed to generate random"))?;
		client.server_challenge = Some(server_challenge);

		let mut hasher = Sha256::new();
		hasher.update(&decrypted);
		let challenge_response_hash = hasher.finalize();

		let mut challenge_response_decrypted = challenge_response_hash.to_vec();
		challenge_response_decrypted.extend(server_challenge);

		aes_encrypt_ecb(&challenge_response_decrypted, key)
			.map_err(|e| tracing::warn!("Failed to encrypt client challenge response: {e}"))
	}

	pub(crate) fn server_challenge_response(
		&self,
		id: &str,
		generation: Option<&str>,
		challenge_response: Vec<u8>,
	) -> Result<Vec<u8>, ()> {
		if challenge_response.len() != 32 {
			return Err(());
		}
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		Self::expire(&mut inner);
		if inner
			.get(id)
			.is_none_or(|client| generation != Some(client.approval.as_str()))
		{
			return Err(());
		}
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;

		if client.client_hash.is_some() || client.server_challenge.is_none() {
			return Err(());
		}

		let key = match &client.key {
			Some(key) => key,
			None => {
				tracing::warn!("Client has not provided a pin yet.");
				return Err(());
			},
		};

		let decrypted = aes_decrypt_ecb(&challenge_response, key)
			.map_err(|e| tracing::warn!("Failed to decrypt server challenge response: {e}"))?;
		client.client_hash = Some(decrypted);

		let server_secret = client.server_secret.ok_or_else(|| {
			tracing::warn!("Client does not have a server secret.");
		})?;

		let mut pairing_secret = server_secret.to_vec();
		let signed = sign(&server_secret, &self.server_private_key_pem)
			.map_err(|e| tracing::warn!("Failed to sign server secret: {e}"))?;
		pairing_secret.extend(signed);

		Ok(pairing_secret)
	}

	pub(crate) fn check_client_pairing_secret(
		&self,
		id: &str,
		generation: Option<&str>,
		client_secret: Vec<u8>,
	) -> Result<(), ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		Self::expire(&mut inner);
		if inner
			.get(id)
			.is_none_or(|client| generation != Some(client.approval.as_str()))
		{
			return Err(());
		}
		// Remove on both cryptographic failure and successful durable completion.
		if inner.get(id).is_none_or(|client| client.key.is_none()) {
			return Err(());
		}
		let mut client = inner.remove(id).ok_or(())?;
		verify_pairing_secret(&mut client, client_secret)
			.map_err(|e| tracing::warn!("Failed to verify client pairing secret: {e}"))?;
		let fingerprint = cert_pem_fingerprint(&client.pem).ok_or(())?;
		self.state.pair(id.to_string(), fingerprint)?;

		Ok(())
	}
}

pub(crate) fn create_key(salt: &[u8; 16], pin: &str) -> Result<[u8; 16], String> {
	let mut key = Vec::with_capacity(salt.len() + pin.len());
	key.extend(salt);
	key.extend(pin.as_bytes());

	let mut hasher = Sha256::new();
	hasher.update(&key);
	let hash = hasher.finalize();

	hash[..16]
		.try_into()
		.map_err(|e| format!("Received unexpected key result: {e}"))
}

pub(crate) fn sign(data: &[u8], key_pem: &str) -> Result<Vec<u8>, String> {
	let key_bytes = {
		let mut reader = std::io::Cursor::new(key_pem.as_bytes());
		match rustls_pemfile::private_key(&mut reader) {
			Ok(Some(key)) => key.secret_der().to_vec(),
			Ok(None) => return Err("No key found in PEM".to_string()),
			Err(e) => return Err(format!("Failed to parse key PEM: {}", e)),
		}
	};

	let key_pair = RsaKeyPair::from_pkcs8(&key_bytes).map_err(|e| format!("Failed to load RSA key pair: {}", e))?;

	let rng = SystemRandom::new();
	let mut signature = vec![0; key_pair.public_key().modulus_len()];

	key_pair
		.sign(&RSA_PKCS1_SHA256, &rng, data, &mut signature)
		.map_err(|e| format!("Failed to sign data: {}", e))?;
	Ok(signature)
}

pub(crate) fn extract_certificate_signature(pem: &str) -> Result<Vec<u8>, String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).map_err(|e| format!("Failed to parse PEM: {}", e))?;
	let cert = pem_obj
		.parse_x509()
		.map_err(|e| format!("Failed to parse X509: {}", e))?;
	Ok(cert.signature_value.data.to_vec())
}

fn verify_client_signature(pem: &str, secret: &[u8], signature: &[u8]) -> Result<(), String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).map_err(|e| format!("Failed to parse PEM: {}", e))?;
	let cert = pem_obj
		.parse_x509()
		.map_err(|e| format!("Failed to parse X509: {}", e))?;
	let public_key_bytes = cert.tbs_certificate.subject_pki.subject_public_key.data;
	let public_key = aws_lc_rs::signature::UnparsedPublicKey::new(&RSA_PKCS1_2048_8192_SHA256, public_key_bytes);
	public_key.verify(secret, signature).map_err(|_| {
		"Client certificate signature verification failed: signature does not match the client's public key".to_string()
	})
}

fn verify_pairing_secret(client: &mut PendingClient, client_secret: Vec<u8>) -> Result<(), String> {
	let client_hash = match &client.client_hash {
		Some(client_hash) => client_hash,
		None => return Err("We did not yet receive a client hash.".to_string()),
	};

	let server_challenge = match client.server_challenge {
		Some(server_challenge) => server_challenge,
		None => {
			return Err("Client does not have a server challenge, possibly incorrect pairing procedure?".to_string());
		},
	};

	if client_secret.len() < 16 {
		return Err(format!(
			"Expected client pairing secret to be at least 16 bytes, but got {}",
			client_secret.len()
		));
	}

	let client_secret_payload = &client_secret[..16];
	let client_signature = &client_secret[16..];

	let mut data = server_challenge.to_vec();

	let signature_bytes = extract_certificate_signature(&client.pem)
		.map_err(|e| format!("Failed to extract client cert signature: {e}"))?;
	data.extend(signature_bytes);
	data.extend(client_secret_payload);

	let mut hasher = Sha256::new();
	hasher.update(&data);
	let hash = hasher.finalize();

	if !hash.to_vec().eq(client_hash) {
		return Err("Client hash is not as expected, MITM?".to_string());
	}

	verify_client_signature(&client.pem, client_secret_payload, client_signature)?;

	Ok(())
}

pub(crate) fn aes_encrypt_ecb(data: &[u8], key: &[u8; 16]) -> Result<Vec<u8>, String> {
	let key: Array<u8, _> = (*key).into();
	let cipher = Aes128::new(&key);
	if !data.len().is_multiple_of(16) {
		return Err(format!("Data length {} not a multiple of 16", data.len()));
	}

	let mut encrypted = data.to_vec();
	for block in encrypted.chunks_mut(16) {
		let gblock: &mut aes::cipher::Array<u8, _> = block.try_into().map_err(|_| "Invalid block length")?;
		cipher.encrypt_block(gblock);
	}
	Ok(encrypted)
}

pub(crate) fn aes_decrypt_ecb(data: &[u8], key: &[u8; 16]) -> Result<Vec<u8>, String> {
	let key: Array<u8, _> = (*key).into();
	let cipher = Aes128::new(&key);
	if !data.len().is_multiple_of(16) {
		return Err(format!("Data length {} not a multiple of 16", data.len()));
	}

	let mut decrypted = data.to_vec();
	for block in decrypted.chunks_mut(16) {
		let gblock: &mut aes::cipher::Array<u8, _> = block.try_into().map_err(|_| "Invalid block length")?;
		cipher.decrypt_block(gblock);
	}
	Ok(decrypted)
}

fn cert_pem_fingerprint(pem: &str) -> Option<String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).ok()?;
	Some(hex::encode(Sha256::digest(&pem_obj.contents)))
}

#[cfg(test)]
mod pairing_lifecycle_tests {
	use super::*;

	fn request(id: &str, pem: &str, seconds: u64) -> PendingClient {
		PendingClient {
			id: id.into(),
			pem: pem.into(),
			salt: [1; 16],
			pin_notify: Arc::new(Notify::new()),
			approval: new_approval_token().unwrap(),
			requester: "192.0.2.1".parse().unwrap(),
			deadline: Instant::now() + Duration::from_secs(seconds),
			key: None,
			server_secret: None,
			server_challenge: None,
			client_hash: None,
		}
	}

	fn certificate() -> String {
		rcgen::generate_simple_self_signed(vec!["test".into()])
			.unwrap()
			.cert
			.pem()
	}

	#[tokio::test(start_paused = true)]
	async fn thousands_of_abandoned_requests_are_bounded_and_expire() {
		let dir = tempfile::tempdir().unwrap();
		let manager = ClientManager::isolated(dir.path().join("state.toml"));
		let shutdown = async_shutdown::ShutdownManager::new();
		manager.ensure_cleanup(shutdown.clone());
		manager.ensure_cleanup(shutdown.clone());
		let pem = certificate();
		let mut admitted = 0;
		for index in 0..5000 {
			if manager
				.start_pairing(request(&format!("client-{index}"), &pem, 360))
				.is_ok()
			{
				admitted += 1;
			}
		}
		assert_eq!(admitted, MAX_PENDING_PAIRINGS);
		assert_eq!(manager.pending_clients.read().unwrap().len(), MAX_PENDING_PAIRINGS);
		assert!(manager.pending_approval("client-0").is_some());
		tokio::task::yield_now().await;
		tokio::time::advance(Duration::from_secs(361)).await;
		tokio::task::yield_now().await;
		assert!(manager.pending_clients.read().unwrap().is_empty());
		assert!(manager.start_pairing(request("after-expiry", &pem, 360)).is_ok());
		shutdown.trigger_shutdown(crate::ShutdownReason::AppQuit).unwrap();
		tokio::task::yield_now().await;
		assert!(manager.pending_clients.read().unwrap().is_empty());
	}

	#[tokio::test]
	async fn early_pin_and_duplicate_generation_cleanup_are_race_free() {
		let dir = tempfile::tempdir().unwrap();
		let manager = ClientManager::isolated(dir.path().join("state.toml"));
		let pem = certificate();
		let original = request("duplicate", &pem, 360);
		let token = original.approval.clone();
		let notify = original.pin_notify.clone();
		manager.start_pairing(original).unwrap();
		manager.register_pin("duplicate", "1234", &token).unwrap();
		// Notify::notify_one retains a permit even before waiter registration.
		tokio::time::timeout(Duration::from_secs(1), notify.notified())
			.await
			.unwrap();
		assert!(manager.approved("duplicate", &token));
		let replacement = request("duplicate", &pem, 360);
		let replacement_token = replacement.approval.clone();
		manager.start_pairing(replacement).unwrap();
		tokio::time::timeout(Duration::from_secs(1), notify.notified())
			.await
			.unwrap();
		assert!(!manager.approved("duplicate", &token));
		manager.register_pin("duplicate", "9999", &replacement_token).unwrap();
		assert!(
			manager
				.client_challenge("duplicate", Some(&token), vec![0; 16])
				.is_err()
		);
		assert!(
			manager
				.server_challenge_response("duplicate", Some(&token), vec![0; 32])
				.is_err()
		);
		assert!(
			manager
				.check_client_pairing_secret("duplicate", Some(&token), vec![0; 272])
				.is_err()
		);
		manager.cancel_pairing("duplicate", &token);
		assert_eq!(
			manager.pending_approval("duplicate").unwrap().approval,
			replacement_token
		);
		assert!(manager.register_pin("duplicate", "1234", &token).is_err());
		manager.cancel_pairing("duplicate", &replacement_token);
		assert!(manager.pending_clients.read().unwrap().is_empty());
	}

	#[test]
	fn repeated_replacements_do_not_accumulate_transactions() {
		let dir = tempfile::tempdir().unwrap();
		let manager = ClientManager::isolated(dir.path().join("state.toml"));
		let pem = certificate();
		for _ in 0..5000 {
			manager.start_pairing(request("duplicate", &pem, 360)).unwrap();
		}
		assert_eq!(manager.pending_clients.read().unwrap().len(), 1);
	}
}
