use std::collections::BTreeMap;
use std::sync::Arc;
use std::sync::RwLock;

use aes::cipher::generic_array::GenericArray;
use aes::cipher::BlockDecrypt;
use aes::cipher::BlockEncrypt;
use aes::cipher::KeyInit;
use aes::Aes128;
use aws_lc_rs::rand::SecureRandom;
use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::KeyPair;
use aws_lc_rs::signature::RsaKeyPair;
use aws_lc_rs::signature::RSA_PKCS1_2048_8192_SHA256;
use aws_lc_rs::signature::RSA_PKCS1_SHA256;
use sha2::Digest;
use sha2::Sha256;
use tokio::sync::Notify;
use x509_parser::prelude::*;

use crate::state::PersistentState;

/// A client that is not yet paired, but in the pairing process.
pub(crate) struct PendingClient {
	/// Unique id of the client.
	pub(crate) id: String,

	/// Client certificate used for secure communication (PEM format).
	pub(crate) pem: String,

	/// Salt provided by the client to use for encryption.
	pub(crate) salt: [u8; 16],

	/// A channel that sends a notification when a PIN has been received for this client.
	pub(crate) pin_notify: Arc<Notify>,

	/// Cryptographic key.
	pub(crate) key: Option<[u8; 16]>,

	/// Server secret as generated by the server.
	pub(crate) server_secret: Option<[u8; 16]>,

	/// Server challenge provided by the client.
	pub(crate) server_challenge: Option<[u8; 16]>,

	/// Cryptographic hash.
	pub(crate) client_hash: Option<Vec<u8>>,
}

/// Manages client pairing state and operations.
///
/// This is a synchronous manager backed by an `Arc<RwLock>`. It holds pending client state
/// (salt, certificates, challenge/response data) and delegates persistent state to `State`.
#[derive(Clone)]
pub struct ClientManager {
	pending_clients: Arc<RwLock<BTreeMap<String, PendingClient>>>,
	state: PersistentState,
	server_cert_pem: String,
	server_private_key_pem: String,
}

impl ClientManager {
	pub fn new(server_cert_pem: String, server_private_key_pem: String) -> Result<Self, ()> {
		Ok(Self {
			pending_clients: Arc::new(RwLock::new(BTreeMap::new())),
			state: PersistentState::new()?,
			server_cert_pem,
			server_private_key_pem,
		})
	}

	pub fn persistent_state(&self) -> &PersistentState {
		&self.state
	}

	pub(crate) fn is_paired(&self, id: String) -> Result<bool, ()> {
		self.state.has_client(id)
	}

	pub(crate) fn is_cert_paired(&self, fingerprint: &str) -> Result<bool, ()> {
		self.state.has_paired_cert(fingerprint.to_string())
	}

	pub(crate) fn start_pairing(&self, pending_client: PendingClient) -> Result<(), ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		inner.insert(pending_client.id.clone(), pending_client);
		Ok(())
	}

	pub(crate) fn register_pin(&self, id: &str, pin: &str) -> Result<(), ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;
		let key = create_key(&client.salt, pin).map_err(|e| tracing::warn!("Failed to create client key: {e}"))?;
		client.key = Some(key);
		client.pin_notify.notify_waiters();
		Ok(())
	}

	pub(crate) fn client_challenge(&self, id: &str, challenge: Vec<u8>) -> Result<Vec<u8>, ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;

		let key = match &client.key {
			Some(key) => key,
			None => {
				tracing::warn!("Client has not provided a pin yet.");
				return Err(());
			},
		};

		let mut server_secret = [0u8; 16];
		SystemRandom::new()
			.fill(&mut server_secret)
			.map_err(|_| tracing::warn!("Failed to generate random"))?;
		client.server_secret = Some(server_secret);

		let mut decrypted =
			aes_decrypt_ecb(&challenge, key).map_err(|e| tracing::warn!("Failed to decrypt client challenge: {e}"))?;

		let signature_bytes = extract_certificate_signature(&self.server_cert_pem)
			.map_err(|e| tracing::warn!("Failed to extract server cert signature: {e}"))?;
		decrypted.extend_from_slice(&signature_bytes);
		decrypted.extend_from_slice(&server_secret);

		let mut server_challenge = [0u8; 16];
		SystemRandom::new()
			.fill(&mut server_challenge)
			.map_err(|_| tracing::warn!("Failed to generate random"))?;
		client.server_challenge = Some(server_challenge);

		let mut hasher = Sha256::new();
		hasher.update(&decrypted);
		let challenge_response_hash = hasher.finalize();

		let mut challenge_response_decrypted = challenge_response_hash.to_vec();
		challenge_response_decrypted.extend(server_challenge);

		aes_encrypt_ecb(&challenge_response_decrypted, key)
			.map_err(|e| tracing::warn!("Failed to encrypt client challenge response: {e}"))
	}

	pub(crate) fn server_challenge_response(&self, id: &str, challenge_response: Vec<u8>) -> Result<Vec<u8>, ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;

		let key = match &client.key {
			Some(key) => key,
			None => {
				tracing::warn!("Client has not provided a pin yet.");
				return Err(());
			},
		};

		let decrypted = aes_decrypt_ecb(&challenge_response, key)
			.map_err(|e| tracing::warn!("Failed to decrypt server challenge response: {e}"))?;
		client.client_hash = Some(decrypted);

		let server_secret = client.server_secret.ok_or_else(|| {
			tracing::warn!("Client does not have a server secret.");
		})?;

		let mut pairing_secret = server_secret.to_vec();
		let signed = sign(&server_secret, &self.server_private_key_pem)
			.map_err(|e| tracing::warn!("Failed to sign server secret: {e}"))?;
		pairing_secret.extend(signed);

		Ok(pairing_secret)
	}

	pub(crate) fn check_client_pairing_secret(&self, id: &str, client_secret: Vec<u8>) -> Result<(), ()> {
		let mut inner = self.pending_clients.write().map_err(|poison| {
			tracing::error!("RwLock poisoned: {poison}");
		})?;
		let client = inner.get_mut(id).ok_or_else(|| {
			tracing::warn!("No known client with id {id}");
		})?;
		verify_pairing_secret(client, client_secret)
			.map_err(|e| tracing::warn!("Failed to verify client pairing secret: {e}"))?;

		let fingerprint = cert_pem_fingerprint(&client.pem);
		if let Some(fp) = &fingerprint {
			self.state
				.add_paired_cert(fp.clone())
				.map_err(|_| tracing::warn!("Failed to persist paired certificate: {fp}"))?;
		}

		let has_client = self
			.state
			.has_client(id.to_string())
			.map_err(|_| tracing::warn!("Failed to check client paired status"))?;
		if !has_client {
			self.state
				.add_client(id.to_string())
				.map_err(|_| tracing::warn!("Failed to persist client '{id}'"))?;
		}

		Ok(())
	}
}

fn create_key(salt: &[u8; 16], pin: &str) -> Result<[u8; 16], String> {
	let mut key = Vec::with_capacity(salt.len() + pin.len());
	key.extend(salt);
	key.extend(pin.as_bytes());

	let mut hasher = Sha256::new();
	hasher.update(&key);
	let hash = hasher.finalize();

	hash[..16]
		.try_into()
		.map_err(|e| format!("Received unexpected key result: {e}"))
}

fn sign(data: &[u8], key_pem: &str) -> Result<Vec<u8>, String> {
	let key_bytes = {
		let mut reader = std::io::Cursor::new(key_pem.as_bytes());
		match rustls_pemfile::private_key(&mut reader) {
			Ok(Some(key)) => key.secret_der().to_vec(),
			Ok(None) => return Err("No key found in PEM".to_string()),
			Err(e) => return Err(format!("Failed to parse key PEM: {}", e)),
		}
	};

	let key_pair = RsaKeyPair::from_pkcs8(&key_bytes).map_err(|e| format!("Failed to load RSA key pair: {}", e))?;

	let rng = SystemRandom::new();
	let mut signature = vec![0; key_pair.public_key().modulus_len()];

	key_pair
		.sign(&RSA_PKCS1_SHA256, &rng, data, &mut signature)
		.map_err(|e| format!("Failed to sign data: {}", e))?;
	Ok(signature)
}

fn extract_certificate_signature(pem: &str) -> Result<Vec<u8>, String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).map_err(|e| format!("Failed to parse PEM: {}", e))?;
	let cert = pem_obj
		.parse_x509()
		.map_err(|e| format!("Failed to parse X509: {}", e))?;
	Ok(cert.signature_value.data.to_vec())
}

fn verify_client_signature(pem: &str, secret: &[u8], signature: &[u8]) -> Result<(), String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).map_err(|e| format!("Failed to parse PEM: {}", e))?;
	let cert = pem_obj
		.parse_x509()
		.map_err(|e| format!("Failed to parse X509: {}", e))?;
	let public_key_bytes = cert.tbs_certificate.subject_pki.subject_public_key.data;
	let public_key = aws_lc_rs::signature::UnparsedPublicKey::new(&RSA_PKCS1_2048_8192_SHA256, public_key_bytes);
	public_key.verify(secret, signature).map_err(|_| {
		"Client certificate signature verification failed: signature does not match the client's public key".to_string()
	})
}

fn verify_pairing_secret(client: &mut PendingClient, client_secret: Vec<u8>) -> Result<(), String> {
	let client_hash = match &client.client_hash {
		Some(client_hash) => client_hash,
		None => return Err("We did not yet receive a client hash.".to_string()),
	};

	let server_challenge = match client.server_challenge {
		Some(server_challenge) => server_challenge,
		None => {
			return Err("Client does not have a server challenge, possibly incorrect pairing procedure?".to_string())
		},
	};

	if client_secret.len() < 16 {
		return Err(format!(
			"Expected client pairing secret to be at least 16 bytes, but got {}",
			client_secret.len()
		));
	}

	let client_secret_payload = &client_secret[..16];
	let client_signature = &client_secret[16..];

	let mut data = server_challenge.to_vec();

	let signature_bytes = extract_certificate_signature(&client.pem)
		.map_err(|e| format!("Failed to extract client cert signature: {e}"))?;
	data.extend(signature_bytes);
	data.extend(client_secret_payload);

	let mut hasher = Sha256::new();
	hasher.update(&data);
	let hash = hasher.finalize();

	if !hash.to_vec().eq(client_hash) {
		return Err("Client hash is not as expected, MITM?".to_string());
	}

	verify_client_signature(&client.pem, client_secret_payload, client_signature)?;

	Ok(())
}

fn aes_encrypt_ecb(data: &[u8], key: &[u8; 16]) -> Result<Vec<u8>, String> {
	let cipher = Aes128::new(GenericArray::from_slice(key));
	if !data.len().is_multiple_of(16) {
		return Err(format!("Data length {} not a multiple of 16", data.len()));
	}

	let mut encrypted = data.to_vec();
	for block in encrypted.chunks_mut(16) {
		let mut gblock = GenericArray::clone_from_slice(block);
		cipher.encrypt_block(&mut gblock);
		block.copy_from_slice(&gblock);
	}
	Ok(encrypted)
}

fn aes_decrypt_ecb(data: &[u8], key: &[u8; 16]) -> Result<Vec<u8>, String> {
	let cipher = Aes128::new(GenericArray::from_slice(key));
	if !data.len().is_multiple_of(16) {
		return Err(format!("Data length {} not a multiple of 16", data.len()));
	}

	let mut decrypted = data.to_vec();
	for block in decrypted.chunks_mut(16) {
		let mut gblock = GenericArray::clone_from_slice(block);
		cipher.decrypt_block(&mut gblock);
		block.copy_from_slice(&gblock);
	}
	Ok(decrypted)
}

fn cert_pem_fingerprint(pem: &str) -> Option<String> {
	let (_, pem_obj) = parse_x509_pem(pem.as_bytes()).ok()?;
	Some(hex::encode(Sha256::digest(&pem_obj.contents)))
}
